export const regionOptions = [
  { id: "Europe/London", name: "London (GMT+0)" },
  { id: "Europe/Paris", name: "Paris (GMT+1)" },
  { id: "Europe/Berlin", name: "Berlin (GMT+1)" },
  { id: "Europe/Madrid", name: "Madrid (GMT+1)" },
  { id: "Europe/Rome", name: "Rome (GMT+1)" },
  { id: "Europe/Amsterdam", name: "Amsterdam (GMT+1)" },
  { id: "Europe/Brussels", name: "Brussels (GMT+1)" },
  { id: "Europe/Oslo", name: "Oslo (GMT+1)" },
  { id: "Europe/Stockholm", name: "Stockholm (GMT+1)" },
  { id: "Europe/Copenhagen", name: "Copenhagen (GMT+1)" },
  { id: "Europe/Warsaw", name: "Warsaw (GMT+1)" },
  { id: "Europe/Prague", name: "Prague (GMT+1)" },
  { id: "Europe/Budapest", name: "Budapest (GMT+1)" },
  { id: "Europe/Athens", name: "Athens (GMT+2)" },
  { id: "Europe/Istanbul", name: "Istanbul (GMT+3)" },
  { id: "Europe/Moscow", name: "Moscow (GMT+3)" },
  { id: "Europe/Helsinki", name: "Helsinki (GMT+2)" },
  { id: "Europe/Bratislava", name: "Bratislava (GMT+1)" },
  { id: "Europe/Vienna", name: "Vienna (GMT+1)" },
  { id: "Europe/Lisbon", name: "Lisbon (GMT)" },
  { id: "Europe/Dublin", name: "Dublin (GMT)" },
  // Add more options as needed
];

export const countryOptions = [
  { id: "AL", name: "Albania" },
  { id: "AD", name: "Andorra" },
  { id: "AT", name: "Austria" },
  { id: "BY", name: "Belarus" },
  { id: "BE", name: "Belgium" },
  { id: "BA", name: "Bosnia and Herzegovina" },
  { id: "BG", name: "Bulgaria" },
  { id: "HR", name: "Croatia" },
  { id: "CY", name: "Cyprus" },
  { id: "CZ", name: "Czech Republic" },
  { id: "DK", name: "Denmark" },
  { id: "EE", name: "Estonia" },
  { id: "FI", name: "Finland" },
  { id: "FR", name: "France" },
  { id: "DE", name: "Germany" },
  { id: "GR", name: "Greece" },
  { id: "HU", name: "Hungary" },
  { id: "IS", name: "Iceland" },
  { id: "IE", name: "Ireland" },
  { id: "IT", name: "Italy" },
  { id: "XK", name: "Kosovo" },
  { id: "LV", name: "Latvia" },
  { id: "LI", name: "Liechtenstein" },
  { id: "LT", name: "Lithuania" },
  { id: "LU", name: "Luxembourg" },
  { id: "MK", name: "North Macedonia" },
  { id: "MT", name: "Malta" },
  { id: "MD", name: "Moldova" },
  { id: "MC", name: "Monaco" },
  { id: "ME", name: "Montenegro" },
  { id: "NL", name: "Netherlands" },
  { id: "NO", name: "Norway" },
  { id: "PL", name: "Poland" },
  { id: "PT", name: "Portugal" },
  { id: "RO", name: "Romania" },
  { id: "RU", name: "Russia" },
  { id: "SM", name: "San Marino" },
  { id: "RS", name: "Serbia" },
  { id: "SK", name: "Slovakia" },
  { id: "SI", name: "Slovenia" },
  { id: "ES", name: "Spain" },
  { id: "SE", name: "Sweden" },
  { id: "CH", name: "Switzerland" },
  { id: "TR", name: "Turkey" },
  { id: "UA", name: "Ukraine" },
  { id: "GB", name: "United Kingdom" },
  { id: "VA", name: "Vatican City" },
  // Add more options as needed
];

export const currencyOptions = [
  { value: "", label: "Currency" },
  { value: "us", label: "US Dollar" },
  { value: "eur", label: "Euro" },
  { value: "gbp", label: "British Pound Sterling" },
  { value: "jpy", label: "Japanese Yen" },
  { value: "cad", label: "Canadian Dollar" },
  { value: "aud", label: "Australian Dollar" },
  { value: "chf", label: "Swiss Franc" },
  { value: "cny", label: "Chinese Yuan" },
  { value: "inr", label: "Indian Rupee" },
  { value: "brl", label: "Brazilian Real" },
  { value: "mxn", label: "Mexican Peso" },
  { value: "rub", label: "Russian Ruble" },
  { value: "zar", label: "South African Rand" },
  { value: "sek", label: "Swedish Krona" },
  { value: "nzd", label: "New Zealand Dollar" },
  { value: "sgd", label: "Singapore Dollar" },
  { value: "hkd", label: "Hong Kong Dollar" },
  // Add more options as needed
];

export const timeZoneOptions = [
  { id: "Europe/London", name: "London (GMT+0)" },
  { id: "Europe/Paris", name: "Paris (GMT+1)" },
  { id: "Europe/Berlin", name: "Berlin (GMT+1)" },
  { id: "Europe/Madrid", name: "Madrid (GMT+1)" },
  { id: "Europe/Rome", name: "Rome (GMT+1)" },
  { id: "Europe/Amsterdam", name: "Amsterdam (GMT+1)" },
  { id: "Europe/Brussels", name: "Brussels (GMT+1)" },
  { id: "Europe/Oslo", name: "Oslo (GMT+1)" },
  { id: "Europe/Stockholm", name: "Stockholm (GMT+1)" },
  { id: "Europe/Copenhagen", name: "Copenhagen (GMT+1)" },
  { id: "Europe/Warsaw", name: "Warsaw (GMT+1)" },
  { id: "Europe/Prague", name: "Prague (GMT+1)" },
  { id: "Europe/Budapest", name: "Budapest (GMT+1)" },
  { id: "Europe/Athens", name: "Athens (GMT+2)" },
  { id: "Europe/Istanbul", name: "Istanbul (GMT+3)" },
  { id: "Europe/Moscow", name: "Moscow (GMT+3)" },
  { id: "Europe/Helsinki", name: "Helsinki (GMT+2)" },
  { id: "Europe/Bratislava", name: "Bratislava (GMT+1)" },
  { id: "Europe/Vienna", name: "Vienna (GMT+1)" },
  { id: "Europe/Lisbon", name: "Lisbon (GMT)" },
  { id: "Europe/Dublin", name: "Dublin (GMT)" },
  // Add more options as needed
];
