export const regionOptions = [
  { value: "", label: "Region" },
  { value: "Europe/London", label: "London (GMT+0)" },
  { value: "Europe/Paris", label: "Paris (GMT+1)" },
  { value: "Europe/Berlin", label: "Berlin (GMT+1)" },
  { value: "Europe/Madrid", label: "Madrid (GMT+1)" },
  { value: "Europe/Rome", label: "Rome (GMT+1)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (GMT+1)" },
  { value: "Europe/Brussels", label: "Brussels (GMT+1)" },
  { value: "Europe/Oslo", label: "Oslo (GMT+1)" },
  { value: "Europe/Stockholm", label: "Stockholm (GMT+1)" },
  { value: "Europe/Copenhagen", label: "Copenhagen (GMT+1)" },
  { value: "Europe/Warsaw", label: "Warsaw (GMT+1)" },
  { value: "Europe/Prague", label: "Prague (GMT+1)" },
  { value: "Europe/Budapest", label: "Budapest (GMT+1)" },
  { value: "Europe/Athens", label: "Athens (GMT+2)" },
  { value: "Europe/Istanbul", label: "Istanbul (GMT+3)" },
  { value: "Europe/Moscow", label: "Moscow (GMT+3)" },
  { value: "Europe/Helsinki", label: "Helsinki (GMT+2)" },
  { value: "Europe/Bratislava", label: "Bratislava (GMT+1)" },
  { value: "Europe/Vienna", label: "Vienna (GMT+1)" },
  { value: "Europe/Lisbon", label: "Lisbon (GMT)" },
  { value: "Europe/Dublin", label: "Dublin (GMT)" },
  // Add more options as needed
];

export const countryOptions = [
  { value: "", label: "Country" },
  { value: "AL", label: "Albania" },
  { value: "AD", label: "Andorra" },
  { value: "AT", label: "Austria" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croatia" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "EE", label: "Estonia" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "GR", label: "Greece" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IE", label: "Ireland" },
  { value: "IT", label: "Italy" },
  { value: "XK", label: "Kosovo" },
  { value: "LV", label: "Latvia" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MK", label: "North Macedonia" },
  { value: "MT", label: "Malta" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "ME", label: "Montenegro" },
  { value: "NL", label: "Netherlands" },
  { value: "NO", label: "Norway" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "SM", label: "San Marino" },
  { value: "RS", label: "Serbia" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "ES", label: "Spain" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "TR", label: "Turkey" },
  { value: "UA", label: "Ukraine" },
  { value: "GB", label: "United Kingdom" },
  { value: "VA", label: "Vatican City" },
  // Add more options as needed
];

export const currencyOptions = [
  { value: "", label: "Currency" },
  { value: "us", label: "US Dollar" },
  { value: "eur", label: "Euro" },
  { value: "gbp", label: "British Pound Sterling" },
  { value: "jpy", label: "Japanese Yen" },
  { value: "cad", label: "Canadian Dollar" },
  { value: "aud", label: "Australian Dollar" },
  { value: "chf", label: "Swiss Franc" },
  { value: "cny", label: "Chinese Yuan" },
  { value: "inr", label: "Indian Rupee" },
  { value: "brl", label: "Brazilian Real" },
  { value: "mxn", label: "Mexican Peso" },
  { value: "rub", label: "Russian Ruble" },
  { value: "zar", label: "South African Rand" },
  { value: "sek", label: "Swedish Krona" },
  { value: "nzd", label: "New Zealand Dollar" },
  { value: "sgd", label: "Singapore Dollar" },
  { value: "hkd", label: "Hong Kong Dollar" },
  // Add more options as needed
];

export const timeZoneOptions = [
  { value: "", label: "Time Zone" },
  { value: "Europe/London", label: "London (GMT+0)" },
  { value: "Europe/Paris", label: "Paris (GMT+1)" },
  { value: "Europe/Berlin", label: "Berlin (GMT+1)" },
  { value: "Europe/Madrid", label: "Madrid (GMT+1)" },
  { value: "Europe/Rome", label: "Rome (GMT+1)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (GMT+1)" },
  { value: "Europe/Brussels", label: "Brussels (GMT+1)" },
  { value: "Europe/Oslo", label: "Oslo (GMT+1)" },
  { value: "Europe/Stockholm", label: "Stockholm (GMT+1)" },
  { value: "Europe/Copenhagen", label: "Copenhagen (GMT+1)" },
  { value: "Europe/Warsaw", label: "Warsaw (GMT+1)" },
  { value: "Europe/Prague", label: "Prague (GMT+1)" },
  { value: "Europe/Budapest", label: "Budapest (GMT+1)" },
  { value: "Europe/Athens", label: "Athens (GMT+2)" },
  { value: "Europe/Istanbul", label: "Istanbul (GMT+3)" },
  { value: "Europe/Moscow", label: "Moscow (GMT+3)" },
  { value: "Europe/Helsinki", label: "Helsinki (GMT+2)" },
  { value: "Europe/Bratislava", label: "Bratislava (GMT+1)" },
  { value: "Europe/Vienna", label: "Vienna (GMT+1)" },
  { value: "Europe/Lisbon", label: "Lisbon (GMT)" },
  { value: "Europe/Dublin", label: "Dublin (GMT)" },
  // Add more options as needed
];
